import { randomBytes, timingSafeEqual } from "node:crypto"
import { asResult } from "@/utils/safe-result"
import { isLocalBindHost } from "./utils/http-utils"

/**
 * Retrieves or generates an authentication token based on the provided configuration and host settings.
 *
 * 1. If a token is explicitly configured, it is returned as-is.
 * 2. If no token is configured and the caller explicitly configured a non-local bind host, a new random token is generated.
 * 3. Finally, no token is returned for all other scenarios.
 *
 * @param {string | undefined} configuredAuthToken The authentication token provided in the configuration, if any.
 * @param {string | undefined} configuredHost The host value explicitly configured by the user/caller, if any.
 * @return {{ authToken?: string; isGenerated: boolean }} An object containing the determined authentication token (if any) and a boolean indicating whether the token was generated by the function.
 */
export function getAuthToken(
  configuredAuthToken: string | undefined,
  configuredHost: string | undefined,
): { authToken?: string; isGenerated: boolean } {
  if (configuredAuthToken) {
    return { authToken: configuredAuthToken, isGenerated: false }
  }

  if (configuredHost && !isLocalBindHost(configuredHost)) {
    return { authToken: randomBytes(32).toString("base64url"), isGenerated: true }
  }

  return { authToken: undefined, isGenerated: false }
}

/**
 * Compares two tokens in a timing-safe manner to prevent timing attacks.
 *
 * @param {string} provided The token provided by the client.
 * @param {string} expected The expected token to compare against.
 * @returns {boolean} True if the tokens match, false otherwise.
 */
export function tokenMatches(provided: string, expected: string): boolean {
  if (provided.length !== expected.length) {
    return false
  }

  const [compareError, isMatch] = asResult(() => timingSafeEqual(Buffer.from(provided), Buffer.from(expected)))
  if (compareError) {
    return false
  }

  return isMatch
}
